from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime

# --------------------------------------------------------------------
# Database Configuration
# --------------------------------------------------------------------
engine = create_engine('sqlite:///ev_charging.db', echo=False)
Base = declarative_base()
Session = sessionmaker(bind=engine)

# --------------------------------------------------------------------
# Station Table (UPDATED to match pipeline + generator)
# --------------------------------------------------------------------
class Station(Base):
    __tablename__ = 'stations'

    station_id = Column(Integer, primary_key=True, autoincrement=True)

    # Core station info
    name = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    street_address = Column(String)
    city = Column(String)
    state = Column(String)
    zip_code = Column(String)
    charger_type = Column(String)
    usage_cost = Column(String)        # Pricing string, parsed in pipeline
    status = Column(String, default='Active')

    # ML + Analytics fields generated in pipeline
    cluster_id = Column(Integer, default=None)

    # These 3 are generated by your NEW generator:
    session_count = Column(Integer, default=0)
    total_energy = Column(Float, default=0.0)      # ← corresponds to total_energy_kwh externally
    total_revenue = Column(Float, default=0.0)

    def __repr__(self):
        return (
            f"<Station(id={self.station_id}, name='{self.name}', city='{self.city}', "
            f"cluster_id={self.cluster_id}, sessions={self.session_count}, status='{self.status}')>"
        )

# --------------------------------------------------------------------
# ChargingSession Table
# --------------------------------------------------------------------
class ChargingSession(Base):
    __tablename__ = 'charging_sessions'

    session_id = Column(Integer, primary_key=True, autoincrement=True)
    station_id = Column(Integer, ForeignKey('stations.station_id'))
    energy_consumed_kwh = Column(Float)
    duration_min = Column(Float)
    cost = Column(Float)
    session_date = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return (
            f"<ChargingSession(id={self.session_id}, station_id={self.station_id}, "
            f"energy={self.energy_consumed_kwh}kWh, cost=${self.cost})>"
        )

# --------------------------------------------------------------------
# User Table
# --------------------------------------------------------------------
class User(Base):
    __tablename__ = 'users'

    user_id = Column(String(50), primary_key=True)
    vehicle_type = Column(String(50))
    battery_capacity = Column(Float)
    preferred_charger = Column(String(50))
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return (
            f"<User(id={self.user_id}, vehicle='{self.vehicle_type}', "
            f"charger='{self.preferred_charger}')>"
        )

# --------------------------------------------------------------------
# Create all tables
# --------------------------------------------------------------------
if __name__ == "__main__":
    Base.metadata.create_all(engine)
    print("✅ Database initialized successfully (aligned with data_pipeline.py and generator)")
